### ISSUE TITLE
Cannot find module 'helius-airship-core' or its corresponding type declarations

### ISSUE THREAD

**Issue by greygoo69** [helius-labs/airship#10]
Why am I getting this error after running `pnpm install` and ensuring i have the correct version of node?

This is what I see when I run `pnpm build`:

<img width="849" alt="image" src="https://github.com/user-attachments/assets/9587137c-ffa8-46f2-af08-a3c19e8ea562">

@KoenRijpstra any ideas?

**Comment by KoenRijpstra** [comment]
If you're running it locally, you'll need to run `pnpm install` and `pnpm build` in the root directory since it's a monorepo.

**Comment by greygoo69** [comment]
Ah, I had to run `pnpm build` in the root dir. I thought it was in the web dir only. Thanks so much, it's working now! 
You might want to update [README.md](https://github.com/helius-labs/airship?tab=readme-ov-file#run-locally-from-source) to include `pnpm build`.
